version: '3.6'
services:
  database:
    container_name: cilist-db
    image: ariretiarno/db-cilist:${GIT_COMMIT_SHORT}
  backend:
    image: ariretiarno/backend-cilist:${GIT_COMMIT_SHORT}
    ports:
    - "5000:5000"
    depends_on:
    - database
    environment:
    - BASE_URL_PORT=5000
    - MYSQL_ROOT_PASSWORD=s3k0l4hd3v0p5
    - DATABASE_USERNAME=people
    - DATABASE_PASSWORD=people
    - DATABASE_DATABASE=people
    - DATABASE_HOST=database
    - DATABASE_PORT=3306
  frontend:
    image: ariretiarno/frontend-cilist:${GIT_COMMIT_SHORT}
    ports:
    - "3000:3000"
    environment:
    - REACT_APP_BACKEND_URL=http://43.200.72.236:5000